### ISSUE TITLE
GHÊ VKL

### ISSUE THREAD

**Issue by tiennampham23** [dokhacchung98/DetectMoveObject#1]
GHÊ VKL
GHÊ VKL
GHÊ VKL
GHÊ VKL
GHÊ VKL
GHÊ VKL
GHÊ VKL
GHÊ VKL

**Comment by dokhacchung98** [comment]
:)

**Comment by dokhacchung98** [comment]
Chưa làm được gì mà bạn đã vào chơi đùa như này rồi, đáng sợ thật 🗡
